### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by Riteo** [godot-italia/linee-guida-traduzione-italiana-godot#2]
Secondo me la parola `script` suonerebbe più intuitiva se fosse tradotta come `codice`, una parola usata già molto frequentemente per riferirsi a un insieme d'istruzioni in un file. Che ne pensate?

**Comment by gioele-santi** [comment]
`script` è un termine che nel tempo ha assunto il significato di **codice/programma interpretato**. `codice` va bene ma ricordiamo che è un termine più generico.

**Comment by Riteo** [comment]
@gioele-santi ricordiamo che su godot uno "script" può essere anche un programma in c#, che non è interpretato.

**Comment by Gaarco** [comment]
`Script` è un termine più specifico di `codice`, a meno che venga in mente un'altra traduzione per ora io appoggio l'idea di lasciarlo non tradotto

**Comment by Riteo** [comment]
@gioele-santi @Gaarco capisco i vostri punti di vista e anch'io ero convinto che script avesse un significato più specifico, ma ho appena controllato e apparentemente [`codice` implica principalmente già una testualità](https://treccani.it/vocabolario/codice) (specialmente a livello etimologico), quindi potremmo discuterne sotto quel punto di vista, se ne siete disposti. Chiederò una piccola mano a quel mio amico con una buona dimestichezza nell'italiano se ne trovo l'opportunità.

Questo rimane comunque obiettivamente un termine piuttosto difficile da bilanciare tra intuitività (un novellino che vuole imparare a programmare si riferirà certamente a un codice in tal maniera, in che non sembra essere sbagliato, vedi sopra) e "accuratezza".
In ogni caso anche `script` mi va bene, pur avendo una preferenza per `codice`, quindi se la maggioranza dice così, che così sia. (Ho notato il tuo pollice in su, ma 2 messaggi con una spiegazione contro un messaggio e una reazione sono leggermente maggiori)

*Piccola nota un po' più fuori luogo: Da notare che sto attento a non trascinare certi traducenti eccessivamente per questioni puramente preferenziali e che se in questo caso ho "insistito" è puramente perché ho trovato informazioni che potrebbero influire sulla conversazione. Come al solito, se inizio a dare fastidio, fatemelo notare :)*
