### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Riteo** [godot-italia/linee-guida-traduzione-italiana-godot#3]
Ho notato come in alcune stringhe la parola `warning`, riferendosi a quelle situazioni non propriamente scorrette ma sconsigliate o potenzialmente problematiche nel codice e quindi non gravi quanto un errore, venga tradotto come `avvertenza`. Apparentemente è sinonimo con `avviso`, un altro traducente comune, quindi andrebbe ben deciso quale sia quello approvato dalla comunità.
Personalmente preferisco `avviso`, essendo anche il traducente più comune che ho notato in giro.

**Comment by gioele-santi** [comment]
`avviso` va bene (penso anche `avvertimento`). 

Bisogna sempre ricordare che nel contesto dei compilatori i principali termini sono `Warning` ed `Error`. 

Mentre `Error` indica qualcosa che impedisce la compilazione e/o l'esecuzione del codice, il `warning` indica qualcosa che *potrebbe* causare problemi in esecuzione oppure altri avvisi che il programmatore vuole darci: "il codice è corretto ma non funziona se non si specifica qualcosa", oppure "questo approccio sarà presto deprecato". 

Altri termini che mi vengono in mente sono `caveat` o `attenzione`, ma non stanno bene in tutti i contesti.

**Comment by Gaarco** [comment]
`Avviso` ed `Errore` per `Warning` ed `Error` credo siano due traduzioni adeguate, per me va bene
