### ISSUE TITLE
Attach a script

### ISSUE THREAD

**Issue by Riteo** [godot-italia/linee-guida-traduzione-italiana-godot#4]
Mentre revisionavo alcune stringhe su weblate, ho notato come la locuzione `to attach a script` mancasse e fosse stata tradotta in più modi.

Solo in una circostanza è stata tradotta come `attribuire uno script`, mentre nel resto dei casi come `allegare uno script`.
Il primo traducente è molto interessante, seppur un po' inusuale. Ignorando il prestito di `script` (#2) onestamente non è che ne sia contro, ma alternative come `collegare uno script`, `associare uno script`, `assegnare uno script` o proprio `allegare uno script` andrebbero alquanto bene a parer mio.

Io tra tutti questi traducenti propongo di aggiungere `assegnare uno script` al glossario.

(modificato perché improvvisamente mi è venuto un sonno tremendo e ho fatto un errore di scrittura)

**Comment by gioele-santi** [comment]
`assegnare uno script` mi sembra il termine migliore nel contesto di Godot.

**Comment by Riteo** [comment]
Problema risolto dopo la commissione di bcc609501ec53f0cc1e2be5cff540684bdb37e24.
