### ISSUE TITLE
Consigli generali

### ISSUE THREAD

**Issue by KaptainMicila** [godot-italia/linee-guida-traduzione-italiana-godot#5]
Sono uno dei tanti traduttori di Godot Engine, e dopo aver letto i commenti di @Riteo su [weblate](https://hosted.weblate.org), mi sono interessato a seguire un filo logico per le traduzioni (perché, ovviamente, non sono l'unico a voler Godot Engine tradotto).
Questa è la mia opinione:

> Evitare di omettere articoli e preposizioni alla "nome di variabile".

Concordo parzialmente: ci sono alcune stringhe che richiedono di essere scritte alla _"nome di variabile"_ per ragioni di spazio. Io concordo con l'idea originale.

Consiglio anche di seguire il Upper Camel Case quando la stringa originale la segue, per favore. Ho trovato fin troppe stringhe che non seguivano il case originale delle parole.

Poi, termini di programmazione (come `Array` o `Build`) è meglio lasciarli come sono.
Spero che questo progetto abbia fortuna. Io continuerò a tradurre il più fedele che posso all'originale. Come già detto su weblate, le **_traduzioni letterali_** feriscono la leggibilità e la comprensione del testo.

**Comment by Riteo** [comment]
@KaptainMicila abbiamo discusso estensivamente su molte di queste cose su discord: https://discord.gg/CryM3fZ
Riguardo all'*Upper Camel Case*, semplicemente non esiste in italiano, e seguire ciecamente l'ortografia di una lingua straniera corrisponde a tradurre letteralmente una frase. Non so se hai letto la proposta originale (piuttosto vecchia), ma dovrei aver accennato qualcosa al riguardo lì.

Piccola domandina un po' più fuori luogo: ma quindi non avevi idea di tutti i piccoli stimoli riguardo alle linee guida? Questa è una vecchia idea della quale ho preso le redini tempo fa, circa a metà 2020 se ricordo bene. Ne ho parlato sul gruppo telegram, ho scritto la proposta sul sito della comunità italiana e c'è stata una buona attività nel server discord. Che sia chiaro, non è un rimprovero, solo una curiosità per capire come informare tutti i traduttori su questa iniziativa.

**Comment by KaptainMicila** [comment]
_La sezione in bold è quella on-topic_

>  abbiamo discusso estensivamente su molte di queste cose su discord: https://discord.gg/CryM3fZ

Grazie per l'invito.

> **Riguardo all'Upper Camel Case, semplicemente non esiste in italiano, e seguire ciecamente l'ortografia di una lingua straniera corrisponde a tradurre letteralmente una frase. Non so se hai letto la proposta originale (piuttosto vecchia), ma dovrei aver accennato qualcosa al riguardo lì.**

**Secondo me non è questione di seguire l'italiano, ma di seguire un [coding standard](https://www.php-fig.org/psr/psr-12/) (questo è di php, ma spero di aver dato l'idea). 
Poi, l'Upper Camel Case per bottoni ed elementi selezionabili serve per una user experience migliore: se il bottone ha un nome troppo lungo, la grafica potrebbe cominciare a buggarsi, e questo è da evitare.**

**Vi parlo da programmatore (2 anni professionalmente, non è assai) che ha provato su se stesso le lamentele di clienti riguardo bottoni con testo troppo lungo.**

> Piccola domandina un po' più fuori luogo: ma quindi non avevi idea di tutti i piccoli stimoli riguardo alle linee guida?

No, mi dispiace.

> Questa è una vecchia idea della quale ho preso le redini tempo fa, circa a metà 2020 se ricordo bene.

Traduco Godot Engine (l'editor, non la documentazione) dall'Agosto 2019. Tristemente non sono riuscito a trovare la guida nemmeno cercandola su google questa sera, mi dispiace (ho dovuto fare l'accesso da github e cercarla nelle issues create). Se avessi saputo dell'esistenza del gruppo, mi sarei chiaramente interfacciato con voi prima di tradurre 30%~40% dell'editor per conto mio.

Se non ci sono altri dubbi sull'Upper Camel Case, la issue può essere chiusa. Per me, deve rimanere.

**Comment by Riteo** [comment]
@KaptainMicila
> Secondo me non è questione di seguire l'italiano, ma di seguire un coding standard

Se vogliamo essere proprio precisi, l'*Upper Camel Case* non richiede spazi. Quello a cui ti stai riferendo, rientra nell'ortografia inglese, ed è il modo in cui vengono scritti i titoli (e, per estensione, il contenuto dei **pulsanti**) in quella lingua. In italiano tutto ciò non esiste. Uno **standard di programmazione** serve ad avere un modo consistente per scrivere programmi, non interfacce. 
Seguire l'italiano è fondamentale in un interfaccia, non essendo limitata da un linguaggio di programmazione, ed è una questione di correttezza generale, proprio com'è importante usare una buona punteggiatura.

Inoltre, lo scopo di una traduzione è quello di risultare comprensibile anche a chi **non** conosce l'inglese, non a chi è esperto e che conosce standard di programmazione. Ti consiglio di leggere le proposte e le discussioni scritte su Discord per avere un'idea degli obiettivi concordati tra me, Gaarco e @gioele-santi. Tutto quello che vedi in questo deposito è stato deciso tra più persone, altra ragione che spiega la sua lentezza nel crescere.

> Poi, l'Upper Camel Case per bottoni ed elementi selezionabili serve per una user experience migliore: se il bottone ha un nome troppo lungo, la grafica potrebbe cominciare a buggarsi, e questo è da evitare.

L'interfaccia di Godot è incredibilmente flessibile, e Weblate ha dei limiti di lunghezza impostati appositamente. Questa considerazione va fatta solo nel caso in cui dia veramente problemi, visto che non è ancora successo. Semmai dovesse succedere comunque andrebbe segnalato anche solo per accorciarne il limite massimo su Weblate.

Per l'aggiunta ti consiglio di vedere altri programmi e avere un'idea del modo in cui sono tradotti, pur prestando attenzione al loro contesto e all'uso degli anglicismi, che abbiamo deciso di evitare il più possibile.

**Comment by Gaarco** [comment]
Per quanto riguarda la lunghezza delle frasi e l'omettere l'articolo in alcuni contesti _potrei_ essere d'accordo, una frase lunga spesso riduce la leggibilità, ovviamente solo nell'editor visto che la documentazione non comporta questo tipo di limitazioni

**Comment by Gaarco** [comment]
Invece per quanto riguarda il [Title Case](https://en.wikipedia.org/wiki/Title_case), secondo me non fa differenza.
Non esiste in italiano, ma non riduce la leggibilità o comprensione, quindi credo si riduca solo a preferenza

**Comment by Riteo** [comment]
> Per quanto riguarda la lunghezza delle frasi e l'omettere l'articolo in alcuni contesti _potrei_ essere d'accordo, una frase lunga spesso riduce la leggibilità, ovviamente solo nell'editor visto che la documentazione non comporta questo tipo di limitazioni

Stessa cosa, ma per ora mi sembra l'idea migliore tentare in questo modo visto che l'interfaccia ce lo permette. Dovesse avere l'effetto contrario ovviamente non c'è nessun problema a toglierlo dalle linee guida stilistiche, specialmente essendo ancora in fase di bozza dove grandi cambiamenti sono da aspettarsi.

> Invece per quanto riguarda il Title Case, secondo me non fa differenza.
Non esiste in italiano, ma non riduce la leggibilità o comprensione, quindi credo si riduca solo a preferenza

Qui non sono d'accordo. Non è una questione di preferenza come non è una questione di preferenza usare male la punteggiatura. È una questione di correttezza ortografica.

**Comment by Riteo** [comment]
Abbiamo discusso su Discord al riguardo, quindi rimaniamo colla maiuscola solo all'inizio? @KaptainMicila ha reagito con un pollice in su riguardo a un messaggio di @gioele-santi che andava contro il *Title Case*. Se mi date l'ok, chiudo il problema.
